name: Docker image pull

on:
 push:
    branches:
        - main
        - dockerimage
 pull_request:
    branches:
        - main
        - dockerimage
 workflow_dispatch:

jobs:
    docker_build_pull:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repository
              uses: action/checkout@v2
            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.dockerusername }}
                password: ${{ secrets.dockerpassword }}
            - name: pull Docker image
              run: docker pull narendrababulinux/nginx:latest
            


