name: Deploy to Azure

on:
  push:
    branches:
      - cibuild

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/setup-azure-cli@v1

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        azureusername: ${{ secrets.AZUREUSERNAME }}
        azurepassword: ${{ secrets.AZUREPASSWORD}}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        #AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        #AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        #AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        
