name: Github workflow

on:
  push:
    branches:
      - main
      - rel/*
  pull_request:
    branches:
      - main
      - rel/*
      - feature/ *

  workflow_dispatch:

jobs:
   runs-on ubuntu-latest
   steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: execute the sh script
        run: |
          echo "test pipeline"
